/**
 * Engine Logger
 * 
 * Provides structured logging for the Orbyt Engine using ecosystem-core utilities.
 * Supports multiple output formats and log levels with proper filtering.
 * 
 * Features:
 * - Severity-based log level filtering using LogLevelSeverity
 * - Multiple output formats (pretty, text, json, structured)
 * - Color support with ANSI codes
 * - Engine-generated timestamps (consistent across CLI, API, web dashboards)
 * - Context and error tracking
 * - Performance measurement with automatic severity adjustment
 * - Efficient level comparison using numeric severity
 * 
 * Timestamps are generated by the engine to ensure consistency across:
 * - CLI output
 * - API responses
 * - Web dashboard logs
 * - Monitoring systems
 * - Audit trails
 * 
 * @module logging
 */

import {
  LogLevel,
  LogLevelSeverity,
  formatLog,
  createLogEntry,
  shouldLog,
  formatTimestamp,
  type LogEntry,
  type LogFormatOptions,
} from '@dev-ecosystem/core';
import {
  type EngineLoggerConfig,
  type EngineLogFormat,
  type EngineLogEvent,
  type ExportedLogs,
  type LogCategory,
  type WorkflowContext,
  EngineLogType,
  LogCategoryEnum,
} from '../types/log-types.js';
import { AsyncLocalStorage } from 'node:async_hooks';
import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

// ─── Internal dispatch interface ──────────────────────────────────────────────

/**
 * Internal contract used by CategoryLogger to call back into EngineLogger
 * without a circular reference.  Not part of the public API.
 * @internal
 */
interface LogDispatcher {
  _logWithCategory(
    level: LogLevel,
    message: string,
    context?: Record<string, unknown>,
    error?: Error,
    category?: LogCategory,
    typeOverride?: EngineLogType,
  ): void;
}

// ─── CategoryLogger ────────────────────────────────────────────────────────────

/**
 * A thin wrapper that pins every log call to a specific category.
 *
 * Obtain instances via `EngineLogger.runtime`, `.analysis`, `.system`, or `.security`.
 *
 * ```typescript
 * const logger = LoggerManager.getLogger();
 *
 * // inside run() — runtime category
 * logger.runtime.info('Step started', { stepId });
 *
 * // inside explain() / validate() — analysis category
 * logger.analysis.debug('Building execution plan');
 * ```
 */
export class CategoryLogger {
  constructor(
    private readonly parent: LogDispatcher,
    private readonly category: LogCategory,
  ) { }

  debug(message: string, context?: Record<string, unknown>): void {
    this.parent._logWithCategory(LogLevel.DEBUG, message, context, undefined, this.category);
  }

  info(message: string, context?: Record<string, unknown>): void {
    this.parent._logWithCategory(LogLevel.INFO, message, context, undefined, this.category);
  }

  warn(message: string, context?: Record<string, unknown>): void {
    this.parent._logWithCategory(LogLevel.WARN, message, context, undefined, this.category);
  }

  error(message: string, error?: Error, context?: Record<string, unknown>): void {
    this.parent._logWithCategory(LogLevel.ERROR, message, context, error, this.category);
  }

  fatal(message: string, error?: Error, context?: Record<string, unknown>): void {
    this.parent._logWithCategory(LogLevel.FATAL, message, context, error, this.category);
  }

  /**
   * Measure execution time of `fn` and log the result under this category.
   *
   * ```typescript
   * const result = await logger.runtime.measureExecution(
   *   'step:http-request',
   *   () => httpAdapter.run(step),
   *   { warn: 3000, error: 10000 },
   * );
   * ```
   */
  async measureExecution<T>(
    label: string,
    fn: () => Promise<T>,
    thresholds?: { warn?: number; error?: number },
  ): Promise<T> {
    const start = Date.now();
    try {
      const result = await fn();
      const duration = Date.now() - start;
      let level = LogLevel.INFO;
      if (thresholds?.error && duration > thresholds.error) level = LogLevel.ERROR;
      else if (thresholds?.warn && duration > thresholds.warn) level = LogLevel.WARN;
      this.parent._logWithCategory(
        level, `${label} completed`,
        { durationMs: duration }, undefined, this.category,
        EngineLogType.EXECUTION_TIME,
      );
      return result;
    } catch (err) {
      const duration = Date.now() - start;
      this.parent._logWithCategory(
        LogLevel.ERROR, `${label} failed`,
        { durationMs: duration },
        err instanceof Error ? err : new Error(String(err)),
        this.category,
        EngineLogType.ERROR_DETECTED,
      );
      throw err;
    }
  }
}

// ─── EngineLogger ──────────────────────────────────────────────────────────────

/**
 * Engine Logger
 *
 * Wraps ecosystem-core logging utilities with engine-specific configuration.
 * Emits structured JSON logs and maintains a typed log history.
 *
 * ### Category sub-loggers
 * Every log is tagged with a phase-based category so tooling / formatters can
 * filter or colour-code entries without parsing the message text.
 *
 * | Sub-logger         | Category     | When to use                                       |
 * |--------------------|--------------|---------------------------------------------------|
 * | `logger.runtime`   | `runtime`    | `run()` — step start/complete/fail/retry          |
 * | `logger.analysis`  | `analysis`   | `explain()` / `validate()` — plan & parse phase   |
 * | `logger.system`    | `system`     | Engine init/shutdown, adapter registration        |
 * | `logger.security`  | `security`   | Reserved-field violations, permission rejections  |
 *
 * Generic `logger.info(...)` etc. fall back to the category set at construction.
 */
export class EngineLogger implements LogDispatcher {
  private static workflowContextStorage = new AsyncLocalStorage<WorkflowContext>();
  private config: Required<EngineLoggerConfig>;
  private formatOptions: LogFormatOptions;
  private logHistory: EngineLogEvent[] = [];
  private readonly fileOutputEnabled: boolean;
  private readonly fileOutputDirectory: string;
  private readonly defaultFileName: string;
  /** Workflow context set by the engine before run/explain/validate */
  private workflowContext: WorkflowContext | null = null;

  // ─── Category sub-loggers ────────────────────────────────────────────────
  /** Use inside `run()` and step-execution paths. Category: `runtime` */
  readonly runtime: CategoryLogger;
  /** Use inside `explain()` and `validate()` paths. Category: `analysis` */
  readonly analysis: CategoryLogger;
  /** Use for engine init, shutdown, adapter registration. Category: `system` */
  readonly system: CategoryLogger;
  /** Use for reserved-field violations, permission rejections. Category: `security` */
  readonly security: CategoryLogger;

  constructor(config: EngineLoggerConfig) {
    this.config = {
      level: config.level,
      format: config.format || 'json',
      colors: config.colors ?? true,
      timestamp: config.timestamp ?? true,
      source: config.source || 'Orbyt',
      structuredEvents: config.structuredEvents ?? true,
      category: config.category || LogCategoryEnum.SYSTEM,
      fileOutput: config.fileOutput ?? {},
      maxHistorySize: config.maxHistorySize ?? 5000,
    };

    this.formatOptions = {
      format: this.config.format,
      colors: this.config.colors,
      timestamp: this.config.timestamp,
      includeSource: true,
    };

    this.fileOutputEnabled = config.fileOutput?.enabled === true;
    this.fileOutputDirectory = config.fileOutput?.directory || '.orbyt/logs';
    this.defaultFileName = config.fileOutput?.fileName || 'engine.json';

    // Bind category sub-loggers
    this.runtime = new CategoryLogger(this, LogCategoryEnum.RUNTIME);
    this.analysis = new CategoryLogger(this, LogCategoryEnum.ANALYSIS);
    this.system = new CategoryLogger(this, LogCategoryEnum.SYSTEM);
    this.security = new CategoryLogger(this, LogCategoryEnum.SECURITY);
  }

  /**
   * Log a debug message
   */
  debug(message: string, context?: Record<string, unknown>): void {
    this.log(LogLevel.DEBUG, message, context);
  }

  /**
   * Log an info message
   */
  info(message: string, context?: Record<string, unknown>): void {
    this.log(LogLevel.INFO, message, context);
  }

  /**
   * Log a warning message
   */
  warn(message: string, context?: Record<string, unknown>): void {
    this.log(LogLevel.WARN, message, context);
  }

  /**
   * Log an error message
   */
  error(message: string, error?: Error, context?: Record<string, unknown>): void {
    this.log(LogLevel.ERROR, message, context, error);
  }

  /**
   * Log a fatal error message
   */
  fatal(message: string, error?: Error, context?: Record<string, unknown>): void {
    this.log(LogLevel.FATAL, message, context, error);
  }

  /**
   * Log with a custom level
   */
  logWithLevel(level: LogLevel, message: string, context?: Record<string, unknown>): void {
    this.log(level, message, context);
  }

  /**
   * Log only if severity meets minimum threshold
   */
  logIfSeverity(
    minSeverity: number,
    level: LogLevel,
    message: string,
    context?: Record<string, unknown>
  ): void {
    if (LogLevelSeverity[level] >= minSeverity) {
      this.log(level, message, context);
    }
  }

  /**
   * Measure and log execution time with appropriate log level based on duration.
   *
   * Pass `category` to override (`'runtime'` during `run()`, `'analysis'` during `explain()`).
   * Prefer `logger.runtime.measureExecution(...)` or `logger.analysis.measureExecution(...)`.
   */
  async measureExecution<T>(
    label: string,
    fn: () => Promise<T>,
    thresholds?: { warn?: number; error?: number },
    category?: LogCategory,
  ): Promise<T> {
    const start = Date.now();
    try {
      const result = await fn();
      const duration = Date.now() - start;

      let level = LogLevel.DEBUG;
      if (thresholds?.error && duration > thresholds.error) {
        level = LogLevel.ERROR;
      } else if (thresholds?.warn && duration > thresholds.warn) {
        level = LogLevel.WARN;
      } else {
        level = LogLevel.INFO;
      }

      this._logWithCategory(level, `${label} completed`, { durationMs: duration }, undefined, category, EngineLogType.EXECUTION_TIME);
      return result;
    } catch (error) {
      const duration = Date.now() - start;
      this._logWithCategory(
        LogLevel.ERROR,
        `${label} failed`,
        { durationMs: duration },
        error instanceof Error ? error : new Error(String(error)),
        category,
        EngineLogType.ERROR_DETECTED,
      );
      throw error;
    }
  }

  // ─── Core log dispatch ────────────────────────────────────────────────────

  /**
   * Central log dispatcher — used directly by `CategoryLogger` sub-loggers
   * and by the private `log()` helper below.
   *
   * @param level            - Severity level
   * @param message          - Human-readable message
   * @param context          - Optional key-value metadata (merged with workflow ctx)
   * @param error            - Optional error object
   * @param categoryOverride - Pin to a specific category (defaults to config category)
   * @param typeOverride     - Explicit `EngineLogType`; inferred from level when omitted
   *
   * @internal  Called via sub-loggers (`runtime`, `analysis`, etc.) or internally.
   */
  _logWithCategory(
    level: LogLevel,
    message: string,
    context?: Record<string, unknown>,
    error?: Error,
    categoryOverride?: LogCategory,
    typeOverride?: EngineLogType,
  ): void {
    if (!this.shouldLogLevel(level)) return;

    // Map severity level → structured event type
    const typeMap: Partial<Record<LogLevel, EngineLogType>> = {
      [LogLevel.DEBUG]: EngineLogType.DEBUG,
      [LogLevel.INFO]: EngineLogType.INFO,
      [LogLevel.WARN]: EngineLogType.WARNING,
      [LogLevel.ERROR]: EngineLogType.ERROR_DETECTED,
      [LogLevel.FATAL]: EngineLogType.ERROR,
    };
    const eventType = typeOverride ?? typeMap[level] ?? EngineLogType.INFO;
    const category = categoryOverride ?? this.config.category;

    // Automatically merge workflow context so every log carries the active workflow
    const enrichedContext: Record<string, unknown> = {};
    const activeWorkflowContext = EngineLogger.workflowContextStorage.getStore() ?? this.workflowContext;
    if (activeWorkflowContext && Object.keys(activeWorkflowContext).length > 0) {
      enrichedContext['workflow'] = { ...activeWorkflowContext };
    }
    if (context) {
      Object.assign(enrichedContext, context);
    }
    const finalContext = Object.keys(enrichedContext).length > 0 ? enrichedContext : undefined;

    // Record in history
    const event: EngineLogEvent = {
      type: eventType,
      timestamp: new Date(),
      message,
      category,
      source: this.config.source,
      context: finalContext,
      error,
    };
    this.logHistory.push(event);

    // Ring-buffer: drop the oldest entry when the limit is reached.
    // Set maxHistorySize=0 explicitly to disable trimming.
    if (this.config.maxHistorySize > 0 && this.logHistory.length > this.config.maxHistorySize) {
      this.logHistory.shift();
    }

    // Build + emit formatted entry
    const entry: LogEntry = createLogEntry(level, message, {
      source: this.config.source,
      context: finalContext,
      error,
    });
    const formatted = formatLog(entry, this.formatOptions);
    console.log(formatted);

    // Best-effort file persistence for operational diagnostics.
    if (this.fileOutputEnabled) {
      try {
        const serializedEvent = {
          level,
          type: event.type,
          timestamp: event.timestamp.toISOString(),
          message: event.message,
          category: event.category,
          source: event.source,
          context: event.context,
          error: event.error
            ? {
              name: event.error.name,
              message: event.error.message,
              stack: event.error.stack,
            }
            : undefined,
        };
        this.appendJsonWorkflowLog(serializedEvent, activeWorkflowContext ?? undefined);
      } catch {
        // Non-fatal by design: file logging failure must not break engine execution.
      }
    }
  }

  private appendJsonWorkflowLog(
    event: Record<string, unknown>,
    workflowContext?: WorkflowContext,
  ): void {
    const logFilePath = this.resolveWorkflowLogFilePath(workflowContext);

    const payload: {
      workflow?: WorkflowContext;
      logs: Record<string, unknown>[];
    } = existsSync(logFilePath)
        ? this.readExistingLogPayload(logFilePath)
        : {
          workflow: workflowContext,
          logs: [],
        };

    if (!payload.workflow && workflowContext) {
      payload.workflow = { ...workflowContext };
    }

    payload.logs.push(event);
    writeFileSync(logFilePath, `${JSON.stringify(payload, null, 2)}\n`, 'utf8');
  }

  private readExistingLogPayload(logFilePath: string): {
    workflow?: WorkflowContext;
    logs: Record<string, unknown>[];
  } {
    try {
      const raw = readFileSync(logFilePath, 'utf8');
      const parsed = JSON.parse(raw) as { workflow?: WorkflowContext; logs?: Record<string, unknown>[] };
      return {
        workflow: parsed.workflow,
        logs: Array.isArray(parsed.logs) ? parsed.logs : [],
      };
    } catch {
      return { logs: [] };
    }
  }

  private resolveWorkflowLogFilePath(workflowContext?: WorkflowContext): string {
    const workflowName = this.sanitizeFileSegment(workflowContext?.name || 'engine');
    const executionId = this.sanitizeFileSegment(workflowContext?.executionId);

    if (executionId) {
      return join(this.fileOutputDirectory, `${workflowName}__${executionId}.json`);
    }

    const defaultName = this.defaultFileName.toLowerCase().endsWith('.json')
      ? this.defaultFileName
      : `${this.defaultFileName}.json`;
    return join(this.fileOutputDirectory, defaultName);
  }

  private sanitizeFileSegment(value?: string): string {
    if (!value) return '';
    const sanitized = value
      .toLowerCase()
      .replace(/[^a-z0-9._-]+/g, '_')
      .replace(/^_+|_+$/g, '');
    return sanitized || 'workflow';
  }

  /**
   * Private shorthand — uses the default category from config.
   * Prefer the categorised sub-loggers (`runtime`, `analysis`, etc.) for new code.
   */
  private log(
    level: LogLevel,
    message: string,
    context?: Record<string, unknown>,
    error?: Error,
  ): void {
    this._logWithCategory(level, message, context, error);
  }

  // ─── Log History ────────────────────────────────────────────────────

  /**
   * Export collected logs as a structured ExportedLogs object.
   * Includes `byCategory` statistics and the active `workflowContext` snapshot.
   */
  exportLogs(): ExportedLogs {
    const grouped: Record<string, EngineLogEvent[]> = {};
    let withErrors = 0;
    let withMetrics = 0;
    let first: Date | undefined;
    let last: Date | undefined;
    const byType: Record<string, number> = {};
    const byCategory: Record<string, number> = {};

    for (const event of this.logHistory) {
      const typeKey = event.type as string;
      grouped[typeKey] = grouped[typeKey] ? [...grouped[typeKey], event] : [event];
      byType[typeKey] = (byType[typeKey] ?? 0) + 1;
      byCategory[event.category] = (byCategory[event.category] ?? 0) + 1;
      if (event.error) withErrors++;
      if (event.metrics) withMetrics++;
      if (!first || event.timestamp < first) first = event.timestamp;
      if (!last || event.timestamp > last) last = event.timestamp;
    }

    return {
      raw: [...this.logHistory],
      grouped,
      workflowContext: this.workflowContext ?? undefined,
      stats: {
        total: this.logHistory.length,
        byType,
        byCategory,
        withErrors,
        withMetrics,
        timeRange: { first, last },
      },
    };
  }

  /**
   * Get all collected logs as a JSON string
   */
  getJSONLogs(): string {
    return JSON.stringify(this.exportLogs(), null, 2);
  }

  /**
   * Clear the log history (does NOT clear the workflow context)
   */
  clearHistory(): void {
    this.logHistory = [];
  }

  // ─── Workflow Context ─────────────────────────────────────────────────────

  /**
   * Attach workflow context so every subsequent log entry automatically
   * includes a `workflow` field.  Call this before `run()`, `explain()`,
   * or `validate()` with the parsed workflow data.
   *
   * ```typescript
   * logger.setWorkflowContext({
   *   name:        workflow.name,
   *   version:     workflow.version,
   *   kind:        workflow.kind,
   *   stepCount:   workflow.steps.length,
   *   filePath:    resolvedPath,
   * });
   * ```
   */
  setWorkflowContext(ctx: WorkflowContext): void {
    const scoped = EngineLogger.workflowContextStorage.getStore();
    if (scoped) {
      for (const key of Object.keys(scoped)) {
        delete (scoped as Record<string, unknown>)[key];
      }
      Object.assign(scoped, ctx);
      return;
    }

    this.workflowContext = { ...ctx };
  }

  /**
   * Detach the workflow context (e.g. after a run completes).
   * Logs emitted after this call will no longer include the `workflow` field.
   */
  clearWorkflowContext(): void {
    const scoped = EngineLogger.workflowContextStorage.getStore();
    if (scoped) {
      for (const key of Object.keys(scoped)) {
        delete (scoped as Record<string, unknown>)[key];
      }
      return;
    }

    this.workflowContext = null;
  }

  /**
   * Returns a read-only snapshot of the currently active workflow context,
   * or `null` if none has been set.
   */
  getWorkflowContext(): Readonly<WorkflowContext> | null {
    const scoped = EngineLogger.workflowContextStorage.getStore();
    if (scoped) {
      return Object.keys(scoped).length > 0 ? { ...scoped } : null;
    }

    return this.workflowContext ? { ...this.workflowContext } : null;
  }

  /**
   * Partially update the active workflow context without replacing it.
   * Only the supplied fields are merged in; the rest are preserved.
   *
   * Useful for enriching the context mid-run (e.g. after the execution
   * strategy is determined):
   *
   * ```typescript
   * logger.patchWorkflowContext({ executionStrategy: 'parallel' });
   * ```
   *
   * If no context has been set yet, the patch is applied as if it were
   * a fresh `setWorkflowContext` call.
   */
  patchWorkflowContext(partial: Partial<WorkflowContext>): void {
    const scoped = EngineLogger.workflowContextStorage.getStore();
    if (scoped) {
      Object.assign(scoped, partial);
      return;
    }

    this.workflowContext = { ...(this.workflowContext ?? {}), ...partial };
  }

  runWithWorkflowContext<T>(ctx: WorkflowContext, fn: () => T): T {
    return EngineLogger.workflowContextStorage.run({ ...ctx }, fn);
  }

  // ─── Dynamic Context Helpers ──────────────────────────────────────────────

  /**
   * Build a log-context object for a step event.
   *
   * Use this wherever you log step lifecycle events so context is consistent:
   * ```typescript
   * logger.runtime.info('Step started', logger.stepCtx({ id: step.id, adapter: step.adapter }));
   * logger.runtime.error('Step failed', error, logger.stepCtx({ id: step.id, adapter: step.adapter }));
   * ```
   */
  stepCtx(step: {
    id: string;
    adapter?: string;
    name?: string;
    [extra: string]: unknown;
  }): Record<string, unknown> {
    const ctx: Record<string, unknown> = { stepId: step.id };
    if (step.adapter) ctx['adapter'] = step.adapter;
    if (step.name) ctx['stepName'] = step.name;
    // Forward any extra fields the caller added
    for (const [k, v] of Object.entries(step)) {
      if (k !== 'id' && k !== 'adapter' && k !== 'name') ctx[k] = v;
    }
    return ctx;
  }

  /**
   * Build a log-context object for a workflow-level event.
   *
   * Returns a flat object suitable for passing as `context` to any log call.
   * If no workflow context is set, returns `{}`.
   *
   * ```typescript
   * logger.system.info('Workflow validated', logger.workflowCtx());
   * ```
   */
  workflowCtx(): Record<string, unknown> {
    return this.workflowContext ? { ...this.workflowContext } : {};
  }

  // ─── Dynamic Lifecycle Helpers ────────────────────────────────────────────

  /**
   * Log workflow execution started (runtime category).
   * Called at the top of `WorkflowExecutor.execute()`.
   */
  workflowStarted(workflowName: string, context?: Record<string, unknown>): void {
    this.runtime.info(`Workflow "${workflowName}" started`, { workflowName, ...context });
  }

  /**
   * Log a workflow input field that was resolved (runtime category).
   */
  inputProcessed(key: string, value: unknown, source: string): void {
    this.runtime.debug(`Input resolved: ${key}`, { key, value, source });
  }

  /**
   * Log a context field used during execution (runtime category).
   */
  fieldExecution(fieldType: string, key: string, value: unknown): void {
    this.runtime.debug(`Context field accessed: ${fieldType}.${key}`, { fieldType, key, value });
  }

  /**
   * Log step execution started (runtime category).
   * ```typescript
   * logger.stepStarted(step.id, step.name, { adapter: step.adapter });
   * ```
   */
  stepStarted(stepId: string, stepName: string, context?: Record<string, unknown>): void {
    this._logWithCategory(
      LogLevel.INFO,
      `Step "${stepName}" (${stepId}) started`,
      { stepId, stepName, ...context },
      undefined,
      LogCategoryEnum.RUNTIME,
      EngineLogType.STEP_STARTED,
    );
  }

  /**
   * Log step execution completed (runtime category).
   */
  stepCompleted(stepId: string, stepName: string, duration: number, context?: Record<string, unknown>): void {
    this._logWithCategory(
      LogLevel.INFO,
      `Step "${stepName}" (${stepId}) completed in ${duration}ms`,
      { stepId, stepName, duration, ...context },
      undefined,
      LogCategoryEnum.RUNTIME,
      EngineLogType.STEP_COMPLETED,
    );
  }

  /**
   * Log step timeout (runtime category).
   */
  stepTimeout(stepId: string, stepName: string, timeoutMs: number): void {
    this._logWithCategory(
      LogLevel.WARN,
      `Step "${stepName}" (${stepId}) timed out after ${timeoutMs}ms`,
      { stepId, stepName, timeoutMs },
      undefined,
      LogCategoryEnum.RUNTIME,
      EngineLogType.STEP_TIMEOUT,
    );
  }

  /**
   * Log step retry attempt (runtime category).
   */
  stepRetry(stepId: string, stepName: string, attempt: number, maxAttempts: number): void {
    this._logWithCategory(
      LogLevel.WARN,
      `Step "${stepName}" (${stepId}) retrying — attempt ${attempt}/${maxAttempts}`,
      { stepId, stepName, attempt, maxAttempts },
      undefined,
      LogCategoryEnum.RUNTIME,
      EngineLogType.STEP_RETRY,
    );
  }

  /**
   * Log step failure after all attempts (runtime category).
   */
  stepFailed(stepId: string, stepName: string, error: Error, context?: Record<string, unknown>): void {
    this._logWithCategory(
      LogLevel.ERROR,
      `Step "${stepName}" (${stepId}) failed: ${error.message}`,
      { stepId, stepName, ...context },
      error,
      LogCategoryEnum.RUNTIME,
      EngineLogType.STEP_FAILED,
    );
  }

  /**
   * Log adapter action execution result (runtime category).
   */
  adapterActionExecuted(adapter: string, action: string, duration: number, success: boolean): void {
    const level = success ? LogLevel.DEBUG : LogLevel.WARN;
    this._logWithCategory(
      level,
      `Adapter "${adapter}" action "${action}" ${success ? 'succeeded' : 'failed'} in ${duration}ms`,
      { adapter, action, duration, success },
      undefined,
      LogCategoryEnum.RUNTIME,
      EngineLogType.EXECUTION_TIME,
    );
  }

  /**
   * Log validation phase started (analysis category).
   */
  validationStarted(type: string, schema: string): void {
    this._logWithCategory(
      LogLevel.DEBUG,
      `Validation started: ${type} against ${schema} schema`,
      { type, schema },
      undefined,
      LogCategoryEnum.ANALYSIS,
      EngineLogType.WORKFLOW_VALIDATION,
    );
  }

  /**
   * Log validation passed (analysis category).
   */
  validationPassed(type: string, schema: string): void {
    this._logWithCategory(
      LogLevel.INFO,
      `Validation passed: ${type} (${schema})`,
      { type, schema },
      undefined,
      LogCategoryEnum.ANALYSIS,
      EngineLogType.WORKFLOW_VALIDATION,
    );
  }

  /**
   * Log validation failure (analysis category).
   */
  validationFailed(type: string, schema: string, errors: string[]): void {
    this._logWithCategory(
      LogLevel.ERROR,
      `Validation failed: ${type} (${schema}) — ${errors.length} error(s)`,
      { type, schema, errors },
      undefined,
      LogCategoryEnum.ANALYSIS,
      EngineLogType.VALIDATION_ERROR,
    );
  }

  /**
   * Log parsing started (analysis category).
   */
  parsingStarted(format: string, source: string): void {
    this._logWithCategory(
      LogLevel.DEBUG,
      `Parsing started: ${format} from ${source}`,
      { format, source },
      undefined,
      LogCategoryEnum.ANALYSIS,
      EngineLogType.INFO,
    );
  }

  /**
   * Log parsing completed (analysis category).
   */
  parsingCompleted(format: string, duration: number, context?: Record<string, unknown>): void {
    this._logWithCategory(
      LogLevel.INFO,
      `Parsing completed: ${format} in ${duration}ms`,
      { format, duration, ...context },
      undefined,
      LogCategoryEnum.ANALYSIS,
      EngineLogType.INFO,
    );
  }

  /**
   * Log parsing failure (analysis category).
   */
  parsingFailed(format: string, error: Error, context?: Record<string, unknown>): void {
    this._logWithCategory(
      LogLevel.ERROR,
      `Parsing failed: ${format} — ${error.message}`,
      { format, ...context },
      error,
      LogCategoryEnum.ANALYSIS,
      EngineLogType.ERROR_DETECTED,
    );
  }

  // ─── Typed Event Logger ───────────────────────────────────────────────────

  /**
   * Emit a log with an explicit `EngineLogType`.
   *
   * Useful when you want the structured event type to be distinct from the
   * generic level-based inference — e.g. to mark a `STEP_RETRY` event:
   *
   * ```typescript
   * logger.logEvent(EngineLogType.STEP_RETRY, LogLevel.WARN, 'Retrying step', {
   *   stepId: 'http-request',
   *   attempt: 2,
   * }, 'runtime');
   * ```
   */
  logEvent(
    type: EngineLogType,
    level: LogLevel,
    message: string,
    context?: Record<string, unknown>,
    category?: LogCategory,
  ): void {
    this._logWithCategory(level, message, context, undefined, category, type);
  }

  // ─── History Queries ──────────────────────────────────────────────────────

  /**
   * Return log events that match every supplied filter field.
   * Omit a field to skip that filter.
   *
   * ```typescript
   * // All runtime errors for the current workflow
   * logger.filterHistory({ category: 'runtime', withErrors: true });
   *
   * // All analysis events since the explain started
   * const since = new Date();
   * logger.filterHistory({ category: 'analysis', since });
   * ```
   */
  filterHistory(filter: {
    category?: LogCategory;
    type?: EngineLogType;
    since?: Date;
    until?: Date;
    source?: string;
    /** Filter to logs that contain a specific workflow name */
    workflowName?: string;
    /** Only return events that have an error attached */
    withErrors?: boolean;
  } = {}): EngineLogEvent[] {
    return this.logHistory.filter(event => {
      if (filter.category && event.category !== filter.category) return false;
      if (filter.type && event.type !== filter.type) return false;
      if (filter.since && event.timestamp < filter.since) return false;
      if (filter.until && event.timestamp > filter.until) return false;
      if (filter.source && event.source !== filter.source) return false;
      if (filter.withErrors && !event.error) return false;
      if (filter.workflowName) {
        const wf = event.context?.['workflow'] as Record<string, unknown> | undefined;
        if (!wf || wf['name'] !== filter.workflowName) return false;
      }
      return true;
    });
  }

  /**
   * Return all history entries grouped by category.
   * Convenience wrapper around `filterHistory`.
   */
  getHistoryByCategory(): Record<LogCategory, EngineLogEvent[]> {
    const result: Record<string, EngineLogEvent[]> = {};
    for (const event of this.logHistory) {
      result[event.category] = result[event.category] ?? [];
      result[event.category].push(event);
    }
    return result as Record<LogCategory, EngineLogEvent[]>;
  }


  /**
   * Check if a level should be logged using severity comparison
   */
  private shouldLogLevel(level: LogLevel): boolean {
    return LogLevelSeverity[level] >= LogLevelSeverity[this.config.level];
  }

  /**
   * Check if a level is more severe than another
   */
  isMoreSevere(level: LogLevel, compareWith: LogLevel): boolean {
    return LogLevelSeverity[level] > LogLevelSeverity[compareWith];
  }

  /**
   * Get severity difference between two levels
   */
  getSeverityDiff(level1: LogLevel, level2: LogLevel): number {
    return LogLevelSeverity[level1] - LogLevelSeverity[level2];
  }

  /**
   * Get the numeric severity of the current log level
   */
  getCurrentSeverity(): number {
    return LogLevelSeverity[this.config.level];
  }

  /**
   * Get the numeric severity of a log level
   */
  getSeverity(level: LogLevel): number {
    return LogLevelSeverity[level];
  }

  /**
   * Update logger configuration
   */
  setLevel(level: LogLevel): void {
    this.config.level = level;
  }

  /**
   * Set level by severity (0-4)
   */
  setLevelBySeverity(severity: number): void {
    const levels = Object.entries(LogLevelSeverity)
      .find(([_, sev]) => sev === severity);
    if (levels) {
      this.config.level = levels[0] as LogLevel;
    }
  }

  /**
   * Update colors setting
   */
  setColors(enabled: boolean): void {
    this.config.colors = enabled;
    this.formatOptions.colors = enabled;
  }

  /**
   * Update format
   */
  setFormat(format: EngineLogFormat): void {
    this.config.format = format;
    this.formatOptions.format = format;
  }

  /**
   * Update timestamp setting
   */
  setTimestamp(enabled: boolean): void {
    this.config.timestamp = enabled;
    this.formatOptions.timestamp = enabled;
  }

  /**
   * Update timestamp format
   * 
   * @param _format - 'time' | 'datetime' | 'full' (reserved for future use)
   */
  setTimestampFormat(_format: 'time' | 'datetime' | 'full'): void {
    // Timestamp format is handled by ecosystem-core formatTimestamp function
    // This method is kept for API compatibility but doesn't modify formatOptions
  }

  /**
   * Format a timestamp using engine's timestamp formatter
   * Useful for consistent timestamp formatting across the system
   * 
   * @param date - Date to format (defaults to current time)
   * @param format - Format type ('time', 'datetime', or 'full')
   * @returns Formatted timestamp string
   */
  formatTimestamp(
    date?: Date,
    format: 'time' | 'datetime' | 'full' = 'time'
  ): string {
    return formatTimestamp(date || new Date(), format);
  }

  /**
   * Check if a level will be logged (uses shouldLog from ecosystem-core)
   */
  willLog(level: LogLevel): boolean {
    return shouldLog(level, this.config.level);
  }

  /**
   * Get current configuration
   */
  getConfig(): Readonly<EngineLoggerConfig> {
    return { ...this.config };
  }

  /**
   * Check if debug logging is enabled
   */
  isDebugEnabled(): boolean {
    return this.willLog(LogLevel.DEBUG);
  }

  /**
   * Check if info logging is enabled
   */
  isInfoEnabled(): boolean {
    return this.willLog(LogLevel.INFO);
  }

  /**
   * Check if warn logging is enabled
   */
  isWarnEnabled(): boolean {
    return this.willLog(LogLevel.WARN);
  }

  /**
   * Check if error logging is enabled
   */
  isErrorEnabled(): boolean {
    return this.willLog(LogLevel.ERROR);
  }
}

/**
 * Create a logger instance from engine config
 */
export function createEngineLogger(
  logLevel: 'debug' | 'info' | 'warn' | 'error' | 'silent',
  verbose: boolean = false
): EngineLogger | null {
  // Silent mode - no logger
  if (logLevel === 'silent') {
    return null;
  }

  // Map engine log level to ecosystem LogLevel
  const levelMap: Record<string, LogLevel> = {
    debug: LogLevel.DEBUG,
    info: LogLevel.INFO,
    warn: LogLevel.WARN,
    error: LogLevel.ERROR,
    fatal: LogLevel.FATAL,
  };

  const level = levelMap[logLevel] || LogLevel.INFO;

  return new EngineLogger({
    level,
    format: verbose ? 'pretty' : 'json',
    colors: true,
    timestamp: true,
    source: 'Orbyt',
    category: LogCategoryEnum.SYSTEM,
    structuredEvents: true,
  });
}

// Re-export types consumed by other engine modules
export type { EngineLoggerConfig, EngineLogFormat };

/**
 * Re-export formatTimestamp for external use
 * Allows other parts of the system to format timestamps consistently
 */
export { formatTimestamp };