import assert from 'node:assert/strict';
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join, resolve } from 'node:path';
import { homedir } from 'node:os';
import { OrbytEngine } from '../../core/OrbytEngine.js';
import { WorkflowLoader } from '../../loader/WorkflowLoader.js';
import type { ParsedWorkflow } from '../../types/core-types.js';

async function run(): Promise<void> {
  const startedAt = Date.now();
  const yamlPath = resolve(process.cwd(), 'examples/workflow.orbt-exec-diagram-test.yaml');
  const orbtDir = join(homedir(), '.orbyt', 'state', 'workflows');
  const orbtPath = join(orbtDir, 'workflow.orbt-exec-diagram-test.orbt');

  const engine = new OrbytEngine({
    enableScheduler: false,
    diagramArtifacts: {
      enabled: true,
      onlyOrbtSources: true,
    },
  });

  let engineStopped = false;

  mkdirSync(orbtDir, { recursive: true });

  // 1) YAML -> ParsedWorkflow (object generation)
  const parsedFromYaml: ParsedWorkflow = await WorkflowLoader.toWorkflowObject(yamlPath);
  assert.equal(parsedFromYaml.kind, 'workflow', 'Expected parsed workflow kind to be workflow');
  assert.ok(parsedFromYaml.steps.length > 0, 'Expected parsed workflow to contain at least one step');

  const orbtObject: ParsedWorkflow = {
    ...parsedFromYaml,
    sourceMetadata: undefined,
  };

  // Persist canonical object as .orbt source artifact.
  writeFileSync(orbtPath, JSON.stringify(orbtObject, null, 2), 'utf-8');
  assert.ok(existsSync(orbtPath), 'Expected .orbt object file to be created');

  try {
    // 2) Execute via .orbt file path (tests .orbt loader path + execution)
    const result = await engine.run(orbtPath, {
      triggeredBy: 'integration-test-orbt',
    });

    assert.equal(result.status, 'success', 'Expected minimal workflow execution to succeed');
    assert.ok(result.executionId, 'Expected executionId to be present');
    assert.ok(result.stepResults.has('hello'), 'Expected hello step result to exist');

    // 3) Internal field injection signal check via usage events generated by engine internals.
    // Stop engine to force usage collector flush before assertions.
    await engine.stop();
    engineStopped = true;

    const usage = await engine.getUsage({
      from: startedAt - 1000,
      to: Date.now() + 1000,
      includeEvents: true,
      limit: 200,
    });

    const events = usage.events || [];
    const executionEvents = events.filter((event) => event.executionId.startsWith('exec_'));
    assert.ok(
      executionEvents.length > 0,
      'Expected usage events with engine-generated internal executionId (exec_...)',
    );

    assert.ok(
      executionEvents.some((event) => event.executionId !== result.executionId),
      'Expected internal execution identity to differ from workflow result executionId',
    );

    // 4) Diagram/index artifact checks for .orbt source relationship mapping.
    const latestDiagram = engine.getLatestWorkflowDiagram(orbtPath);
    assert.ok(latestDiagram, 'Expected latest diagram entry for .orbt source');

    assert.ok(
      latestDiagram?.latest.graphPath && existsSync(latestDiagram.latest.graphPath),
      'Expected graph artifact file to exist',
    );
    assert.ok(
      latestDiagram?.latest.tracePath && existsSync(latestDiagram.latest.tracePath),
      'Expected trace artifact file to exist',
    );
    assert.ok(
      latestDiagram?.latest.mermaidPath && existsSync(latestDiagram.latest.mermaidPath),
      'Expected mermaid artifact file to exist',
    );

    const diagramIndex = engine.getWorkflowDiagramIndex();
    assert.ok(
      diagramIndex.entries[orbtPath],
      'Expected diagram index to map source .orbt path to generated artifacts',
    );

    // Extra validation: generated .orbt source remains readable object JSON.
    const persisted = JSON.parse(readFileSync(orbtPath, 'utf-8')) as ParsedWorkflow;
    assert.equal(persisted.version, parsedFromYaml.version);
    assert.equal(persisted.kind, parsedFromYaml.kind);

    console.log('[orbt-workflow-execution-diagram] PASS', {
      yamlPath,
      orbtPath,
      executionId: result.executionId,
      workflowStatus: result.status,
      diagrams: {
        graphPath: latestDiagram?.latest.graphPath,
        tracePath: latestDiagram?.latest.tracePath,
        mermaidPath: latestDiagram?.latest.mermaidPath,
      },
      indexPath: join(homedir(), '.orbyt', 'state', 'diagrams', 'index.json'),
    });
  } finally {
    if (!engineStopped) {
      await engine.stop();
    }
  }
}

run().catch((error) => {
  console.error('[orbt-workflow-execution-diagram] FAIL:', error);
  process.exitCode = 1;
});
