/**
 * CLI Logger
 * 
 * Wraps EngineLogger from @orbytautomation/engine for CLI-specific use.
 * Timestamps are generated by the engine, ensuring consistency across
 * CLI, API, web dashboards, and other integrations.
 * 
 * Features inherited from EngineLogger:
 * - Severity-based log level filtering using LogLevelSeverity
 * - Multiple output formats (pretty, text, json, structured)
 * - Color support with ANSI codes
 * - Engine-generated timestamps (consistent across all platforms)
 * - Context and error tracking
 * - Performance measurement with automatic severity adjustment
 * 
 * @module utils
 */

import {
  LoggerManager,
  type EngineLoggerConfig,
  type EngineLogFormat,
} from '@orbytautomation/engine';
import { LogLevel } from '@dev-ecosystem/core';

/**
 * CLI log format type (re-exported from engine)
 */
export type CliLogFormat = EngineLogFormat;

/**
 * CLI log context (key-value pairs)
 */
export type CliLogContext = Record<string, unknown>;

/**
 * CLI Logger configuration (extends engine logger config)
 */
export interface CliLoggerConfig extends EngineLoggerConfig {
  /** CLI-specific context (merged with log context) */
  context?: CliLogContext;
  /** Log level for CLI logger */
  level?: LogLevel;
  /** Output format for CLI logger */
  format?: CliLogFormat;
  /** Enable/disable colors */
  colors?: boolean;
  /** Enable/disable timestamps */
  timestamp?: boolean;
}

/**
 * Get the LoggerManager singleton instance
 * Use this for all logging and log access in CLI and formatters.
 */
export function getLoggerManager() {
  return LoggerManager;
}

/**
 * Get the EngineLogger instance from LoggerManager
 */
export function getEngineLogger() {
  return LoggerManager.getLogger();
}

/**
 * Reset the LoggerManager instance (useful for testing)
 */
export function resetLoggerManager(): void {
  LoggerManager.reset();
}

/**
 * CLI Logger class
 * 
 * Wraps the singleton EngineLogger for CLI-specific use.
 * All logging functionality and timestamps come from EngineLogger.
 * This ensures consistency across CLI, API, web dashboards, etc.
 */
export class CliLogger {
  private cliContext: CliLogContext;

  constructor(config: Partial<CliLoggerConfig> = {}) {
    // Always use LoggerManager.getLogger() for logging
    // Configuration should be done via LoggerManager.initialize() before creating CLI logger
    if (config.level !== undefined) {
      LoggerManager.getLogger().setLevel(config.level);
    }
    if (config.colors !== undefined) {
      LoggerManager.getLogger().setColors(config.colors);
    }
    if (config.format !== undefined) {
      LoggerManager.getLogger().setFormat(config.format);
    }
    if (config.timestamp !== undefined) {
      LoggerManager.getLogger().setTimestamp(config.timestamp);
    }

    this.cliContext = config.context ?? {};
  }

  /**
   * Get the underlying EngineLogger instance (from LoggerManager)
   */
  getEngineLogger() {
    return LoggerManager.getLogger();
  }

  /**
   * Get CLI-specific context
   */
  getCliContext(): Readonly<CliLogContext> {
    return { ...this.cliContext };
  }

  /**
   * Set CLI-specific context that will be merged with all logs
   */
  setCliContext(context: CliLogContext): void {
    this.cliContext = context;
  }

  /**
   * Merge additional context into existing CLI context
   */
  addCliContext(context: CliLogContext): void {
    this.cliContext = { ...this.cliContext, ...context };
  }

  /**
   * Set log level
   */
  setLevel(level: LogLevel): void {
    LoggerManager.getLogger().setLevel(level);
  }

  /**
   * Get current log level
   */
  getLevel(): LogLevel {
    return LoggerManager.getLogger().getConfig().level;
  }

  /**
   * Set colors enabled/disabled
   */
  setColors(enabled: boolean): void {
    LoggerManager.getLogger().setColors(enabled);
  }

  /**
   * Check if a log level is enabled
   */
  isLevelEnabled(level: LogLevel): boolean {
    return LoggerManager.getLogger().willLog(level);
  }

  /**
   * Convenience methods for checking specific levels
   */
  isDebugEnabled(): boolean {
    return LoggerManager.getLogger().isDebugEnabled();
  }

  isInfoEnabled(): boolean {
    return LoggerManager.getLogger().isInfoEnabled();
  }

  isWarnEnabled(): boolean {
    return LoggerManager.getLogger().isWarnEnabled();
  }

  isErrorEnabled(): boolean {
    return LoggerManager.getLogger().isErrorEnabled();
  }

  isFatalEnabled(): boolean {
    // Fatal is higher severity than error, so if error is enabled, fatal is too
    return LoggerManager.getLogger().willLog(LogLevel.FATAL);
  }

  /**
   * Log methods - delegate to EngineLogger with merged CLI context
   * All timestamp handling is done by EngineLogger
   */
  debug(message: string, context?: Record<string, unknown>): void {
    LoggerManager.getLogger().debug(message, { ...this.cliContext, ...context });
  }

  info(message: string, context?: Record<string, unknown>): void {
    LoggerManager.getLogger().info(message, { ...this.cliContext, ...context });
  }

  warn(message: string, context?: Record<string, unknown>): void {
    LoggerManager.getLogger().warn(message, { ...this.cliContext, ...context });
  }

  error(message: string, error?: Error, context?: Record<string, unknown>): void {
    LoggerManager.getLogger().error(message, error, { ...this.cliContext, ...context });
  }

  fatal(message: string, error?: Error, context?: Record<string, unknown>): void {
    LoggerManager.getLogger().fatal(message, error, { ...this.cliContext, ...context });
  }

  /**
   * Measure execution time with automatic severity-based logging
   */
  async measureExecution<T>(
    label: string,
    fn: () => Promise<T>,
    thresholds?: { warn?: number; error?: number }
  ): Promise<T> {
    return LoggerManager.getLogger().measureExecution(label, fn, thresholds);
  }

  /**
   * Get all JSON logs from LoggerManager
   */
  getJsonLogs(): any[] {
    return LoggerManager.getJSONLogs();
  }

  /**
   * Get logs filtered by log level
   */
  getLogsByLevel(level: LogLevel): any[] {
    return this.getJsonLogs().filter(log => log.level === level);
  }

  /**
   * Get logs filtered by log type
   */
  getLogsByType(type: string): any[] {
    return this.getJsonLogs().filter(log => log.type === type);
  }

  /**
   * Format logs for CLI output by log level
   */
  formatLogsByLevel(level: LogLevel, verbose = false): string[] {
    return this.getLogsByLevel(level).map(log => formatJsonEvent(log, verbose));
  }

  /**
   * Format all logs for CLI output
   */
  formatAllLogs(verbose = false): string[] {
    return this.getJsonLogs().map(log => formatJsonEvent(log, verbose));
  }
}

/**
 * Create a CLI logger instance
 * 
 * Factory function for creating CLI loggers with engine-generated timestamps.
 */
export function createCliLogger(config?: Partial<CliLoggerConfig>): CliLogger {
  return new CliLogger(config);
}

/**
 * Get the LoggerManager singleton for CLI and formatters
 */
export function getCliLoggerManager() {
  return LoggerManager;
}

// ==================== JSON Formatting Helpers for JSONFormatter ====================

/**
 * Get structured JSON logs from LoggerManager
 */
export function getCliJsonLogs() {
  return LoggerManager.getJSONLogs();
}

/**
 * Format CLI event as JSON string
 * 
 * Used by JsonFormatter to output events in NDJSON format.
 * Each event is a single line of JSON output.
 */
export function formatJsonEvent(event: unknown, verbose = false): string {
  const eventObj = event && typeof event === 'object' ? event as Record<string, unknown> : {};
  const jsonEvent = {
    ...eventObj,
    timestamp: event && typeof event === 'object' && 'timestamp' in event
      ? (event as any).timestamp.toISOString()
      : new Date().toISOString(),
  };

  return verbose
    ? JSON.stringify(jsonEvent, null, 2)
    : JSON.stringify(jsonEvent);
}

/**
 * Format workflow result as JSON string
 * 
 * Used by JsonFormatter to output final workflow result.
 */
export function formatJsonResult(result: unknown, verbose = false): string {
  // Convert Map stepResults to plain object for JSON serialization
  if (result && typeof result === 'object' && 'stepResults' in result) {
    const resultObj = result as any;
    const stepResultsArray: Array<[string, any]> = [];

    if (resultObj.stepResults instanceof Map) {
      for (const [key, value] of resultObj.stepResults.entries()) {
        stepResultsArray.push([key, value]);
      }
    }

    const jsonResult = {
      ...resultObj,
      stepResults: Object.fromEntries(stepResultsArray),
      error: resultObj.error ? {
        message: resultObj.error.message,
        name: resultObj.error.name,
        stack: verbose ? resultObj.error.stack : undefined,
      } : undefined,
    };

    return verbose
      ? JSON.stringify(jsonResult, null, 2)
      : JSON.stringify(jsonResult);
  }

  return verbose
    ? JSON.stringify(result, null, 2)
    : JSON.stringify(result);
}

/**
 * Format error as JSON string
 * 
 * Used by JsonFormatter to output errors in structured format.
 */
export function formatJsonError(error: Error): string {
  const jsonError = {
    type: 'error',
    timestamp: new Date().toISOString(),
    error: {
      message: error.message,
      name: error.name,
      stack: error.stack,
    },
  };

  return JSON.stringify(jsonError, null, 2);
}
